uint64 timestamp			# time since system start (microseconds)

# Longitudinal controllers testing
bool airspeed_mode 			# airspeed mode enabler
bool climbrate_mode  			# climbrate mode enabler
bool altitude_mode			# altitude mode enabler
bool roll_angle_mode			# roll angle mode enabler
bool ct_mode				# cross track mode enabler
bool sideslip_mode			# sideslip mode enabler
bool mpc_airspeed_mode			# mpc airspeed mode enabler
bool mpc_altitude_mode			# mpc altitude mode enabler
bool mpc_ramp_mode			# mpc ramp mode enabler
bool land_mode				# classical controller state machine mode enabler
bool mpc_land_mode 			# mpc controller state machine mode enabler
