uint64 timestamp			# time since system start (microseconds)

# Longitudinal controllers testing
float32 airspeed_step 			# airspeed step from trim value
float32 climbrate_step  		# climbrate step from zero m/s
float32 altitude_step			# altitude step from default value
float32 roll_angle_step			# altitude step from default value
float32 ct_err_step			# altitude step from default value
float32 sideslip_step			# altitude step from default value
float32 mpc_airspeed_step		# mpc airspeed step from default value
float32 mpc_altitude_step		# mpc altitude step from default value
float32 mpc_altitude_ramp		# mpc ramp from default value
