uint64 timestamp			# time since system start (microseconds)

float32 y_ct                            #y cross track state
float32 beta                            #beta state
float32 href				#altitude referance
float32 vref				#airspeed referance
float32 hdotref				#climbrate referance
float32 yref				#crosstrack error referance
float32 betaref				#sideslip referance
float32 phiref				#roll angle referance
float32 phi                             #roll angle
float32 h				#altitude
float32 hdot				#climbrate
