uint64 timestamp			# time since system start (microseconds)

float32 y_ct                            #y cross track state
float32 yaw                            #beta state
float32 href				#altitude referance
float32 vref				#airspeed referance
float32 hdotref				#climbrate referance
float32 yref				#crosstrack error referance
float32 yawref				#sideslip referance
float32 phiref				#roll angle referance
float32 phi                             #roll angle
float32 h				#altitude
float32 hdot				#climbrate
float32 v                               #airspeed
float32 da				#aileron deflection
float32 de				#elevator deflection
float32 dr				#rudder deflection
float32 df				#flap deflection
float32 dt				#thrust
float32 cw_ref				#NSADLC referance
float32 bw_ref				#LSA referance
float32 p_ref				#roll rate referance
float32 mpc_href			#MPC altitude referance
float32 mpc_vref			#MPC airspeed referance
float32 sm_state			#State Machine State
float32 x_it				#x intrack state
float32 l_t				#L_track maximum intrack distance
float32 theta                           #pitch angle
