uint64 timestamp			# time since system start (microseconds)

bool decrab_mp                          #decrab option for moving platform mode
bool virtual_car      			#virtual car in hardware option
bool decrab_runway                      #decrab option for runway landing mode
float32 vp_alt_adjust			#virtual platfrom altitude offset
bool lp_rel_vel				#landing point algorithm relative gps velocity option
